In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=np.arange(15,30).reshape(5,3)
dfx=pd.DataFrame(data,index=['candy','toblerone','kopiko','mars','snickers'],columns=['store1','store2','store3'])
dfx

           store1  store2  store3
candy          15      16      17
toblerone      18      19      20
kopiko         21      22      23
mars           24      25      26
snickers       27      28      29

In [ ]:
dfx['store4']=np.nan
dfx.loc['twix']=np.arange(15,19)
dfx.loc['kitkat']=np.nan
dfx['store5']=np.nan
dfx['store4']['candy']=20
dfx

/tmp/ipykernel_3544/1951821161.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['candy']=20

           store1  store2  store3  store4  store5
candy        15.0    16.0    17.0    20.0     NaN
toblerone    18.0    19.0    20.0     NaN     NaN
kopiko       21.0    22.0    23.0     NaN     NaN
mars         24.0    25.0    26.0     NaN     NaN
snickers     27.0    28.0    29.0     NaN     NaN
twix         15.0    16.0    17.0    18.0     NaN
kitkat        NaN     NaN     NaN     NaN     NaN

In [ ]:
dfx.isnull()

           store1  store2  store3  store4  store5
candy       False   False   False   False    True
toblerone   False   False   False    True    True
kopiko      False   False   False    True    True
mars        False   False   False    True    True
snickers    False   False   False    True    True
twix        False   False   False   False    True
kitkat       True    True    True    True    True

In [ ]:
dfx.notnull()

           store1  store2  store3  store4  store5
candy        True    True    True    True   False
toblerone    True    True    True   False   False
kopiko       True    True    True   False   False
mars         True    True    True   False   False
snickers     True    True    True   False   False
twix         True    True    True    True   False
kitkat      False   False   False   False   False

In [ ]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [ ]:
dfx.isnull().sum().sum()

np.int64(15)

In [ ]:
dfx.count()

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

In [ ]:
dfx.store4[dfx.store4.notnull()]

candy    20.0
twix     18.0
Name: store4, dtype: float64

In [ ]:
dfx.store4.dropna()

candy    20.0
twix     18.0
Name: store4, dtype: float64

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [ ]:
dfx.dropna(how='all')

           store1  store2  store3  store4  store5
candy        15.0    16.0    17.0    20.0     NaN
toblerone    18.0    19.0    20.0     NaN     NaN
kopiko       21.0    22.0    23.0     NaN     NaN
mars         24.0    25.0    26.0     NaN     NaN
snickers     27.0    28.0    29.0     NaN     NaN
twix         15.0    16.0    17.0    18.0     NaN

In [ ]:
dfx.dropna(how='all',axis=1)

           store1  store2  store3  store4
candy        15.0    16.0    17.0    20.0
toblerone    18.0    19.0    20.0     NaN
kopiko       21.0    22.0    23.0     NaN
mars         24.0    25.0    26.0     NaN
snickers     27.0    28.0    29.0     NaN
twix         15.0    16.0    17.0    18.0
kitkat        NaN     NaN     NaN     NaN

In [ ]:
dfx.dropna(thresh=5,axis=1)

           store1  store2  store3
candy        15.0    16.0    17.0
toblerone    18.0    19.0    20.0
kopiko       21.0    22.0    23.0
mars         24.0    25.0    26.0
snickers     27.0    28.0    29.0
twix         15.0    16.0    17.0
kitkat        NaN     NaN     NaN

In [ ]:
ar1=np.array([100,200,np.nan,300])
ser1=pd.Series(ar1)
ar1.mean()
ser1.mean()

np.float64(200.0)

In [ ]:
ser2=dfx.store4
ser2.sum()

np.float64(38.0)

In [ ]:
ser2.mean()

np.float64(19.0)

In [ ]:
ser2.cumsum()

candy        20.0
toblerone     NaN
kopiko        NaN
mars          NaN
snickers      NaN
twix         38.0
kitkat        NaN
Name: store4, dtype: float64

In [ ]:
filledDf=dfx.fillna(0)
filledDf

           store1  store2  store3  store4  store5
candy        15.0    16.0    17.0    20.0     0.0
toblerone    18.0    19.0    20.0     0.0     0.0
kopiko       21.0    22.0    23.0     0.0     0.0
mars         24.0    25.0    26.0     0.0     0.0
snickers     27.0    28.0    29.0     0.0     0.0
twix         15.0    16.0    17.0    18.0     0.0
kitkat        0.0     0.0     0.0     0.0     0.0

In [ ]:
dfx.mean()

store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64

In [ ]:
filledDf.mean()

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

In [ ]:
dfx.store4.fillna(method='ffill')

/tmp/ipykernel_3544/4057730406.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')

candy        20.0
toblerone    20.0
kopiko       20.0
mars         20.0
snickers     20.0
twix         18.0
kitkat       18.0
Name: store4, dtype: float64

In [ ]:
dfx.store4.fillna(method='bfill')

/tmp/ipykernel_3544/1219575873.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')

candy        20.0
toblerone    18.0
kopiko       18.0
mars         18.0
snickers     18.0
twix         18.0
kitkat        NaN
Name: store4, dtype: float64

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,SimpleImputer

In [ ]:
df=pd.DataFrame({"Age":[25,np.nan,30,45,22], "Salary":[50000,60000,np.nan,80000,45000],"Category":["A","B","A",np.nan,"B"]})
df

    Age   Salary Category
0  25.0  50000.0        A
1   NaN  60000.0        B
2  30.0      NaN        A
3  45.0  80000.0      NaN
4  22.0  45000.0        B

In [ ]:
mean_imputer=SimpleImputer(strategy='mean')
df["Age_Mean"]=mean_imputer.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE
0  25.0  50000.0        A      25.0        50000.0  25.000000  50000.000000
1   NaN  60000.0        B      30.5        60000.0  31.766487  60000.000000
2  30.0      NaN        A      30.0        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN      45.0        80000.0  45.000000  80000.000000
4  22.0  45000.0        B      22.0        45000.0  22.000000  45000.000000

In [ ]:
median_imputer=SimpleImputer(strategy='median')
df["Salary_Median"]=median_imputer.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE
0  25.0  50000.0        A      25.0        50000.0  25.000000  50000.000000
1   NaN  60000.0        B      30.5        60000.0  31.766487  60000.000000
2  30.0      NaN        A      30.0        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN      45.0        80000.0  45.000000  80000.000000
4  22.0  45000.0        B      22.0        45000.0  22.000000  45000.000000

In [ ]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
df

,Age,Salary,Category,Age_Mean,Salary_Median,Age_MICE,Salary_MICE,Category_Mode
0,25.0,50000.0,A,25.0,50000.0,25.000000,50000.000000,A
1,NaN,60000.0,B,30.5,60000.0,31.766487,60000.000000,B
2,30.0,NaN,A,30.0,55000.0,30.000000,57324.583367,A
3,45.0,80000.0,NaN,45.0,80000.0,45.000000,80000.000000,A
4,22.0,45000.0,B,22.0,45000.0,22.000000,45000.000000,B

In [ ]:
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
print(df)

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE  \
0  25.0  50000.0        A      25.0        50000.0  25.000000  50000.000000
1   NaN  60000.0        B      30.5        60000.0  31.766487  60000.000000
2  30.0      NaN        A      30.0        55000.0  30.000000  57324.583367
3  45.0  80000.0      NaN      45.0        80000.0  45.000000  80000.000000
4  22.0  45000.0        B      22.0        45000.0  22.000000  45000.000000

  Category_Mode
0             A
1             B
2             A
3             A
4             B