In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dffb1=pd.DataFrame({'players': ['messi','lamine','neymar','ronaldo','mbappe','haaland'], 'Goals': [22,7,6,15,19,10]})
dffb2=pd.DataFrame({'players': ['martinez','ferran','cubarsi','williams','bellingham','neymar'],'Goals':[0,8,9,4,3,6]})

In [ ]:
dfFB1=pd.concat([dffb1,dffb2],ignore_index=True)
dfFB1

       players  Goals
0        messi     22
1       lamine      7
2       neymar      6
3      ronaldo     15
4       mbappe     19
5      haaland     10
6     martinez      0
7       ferran      8
8      cubarsi      9
9     williams      4
10  bellingham      3
11      neymar      6

In [ ]:
df=dffb1.merge(dffb2,how='inner')
df

  players  Goals
0  neymar      6

In [ ]:
df=dffb1.merge(dffb2,how='left')
df

   players  Goals
0    messi     22
1   lamine      7
2   neymar      6
3  ronaldo     15
4   mbappe     19
5  haaland     10

In [ ]:
df=dffb1.merge(dffb2,how='right')
df

      players  Goals
0    martinez      0
1      ferran      8
2     cubarsi      9
3    williams      4
4  bellingham      3
5      neymar      6

In [ ]:
data=np.arange(15).reshape((3,5))
indexers=['rainfall','humidity','wind']
dframe1=pd.DataFrame(data,index=indexers,columns=['Bergen','Oslo','Trondheim','Stavanger','Kritiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kritiansand
rainfall       0     1          2          3            4
humidity       5     6          7          8            9
wind          10    11         12         13           14

In [ ]:
stacked=dframe1.stack()
stacked
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kritiansand
rainfall       0     1          2          3            4
humidity       5     6          7          8            9
wind          10    11         12         13           14

In [ ]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

In [ ]:
frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN